config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
 
  resources :users do 
    resources :decks 
  end

  get '/deck_search' => "deck_searches#show"
  get '/admin_resources' => "admin_resources#show"
  resources :admin_decks

  #=> NEED TO ENCORPORATE ADMIN EDITING ABILITIES HERE
  resources :decks #=> should any be excluded? - maybe :new?

  resources :visitors, only: [:index]
  resources :errors, only: [:index]
   
  get '/api/decks' => "api#decks"

end

app/models/API.rb
class API 

    def self.decks
        @decks = Deck.all.where("level > 0").map{ |deck| deck.with_cards }
    end

end

app/models/admin_deck.rb
class AdminDeck < Deck
    validates :original_deck, uniqueness: true

    def self.new_from_existing(deck_object, admin_id)
        deck_hash = {
            name: deck_object.name,
            level: deck_object.level,
            user_id: admin_id,
            original_deck: deck_object.id
        }
        @admin_deck = self.new(deck_hash)
        deck_object.cards.each{|card| @admin_deck.cards.build({ english: card.english, spanish: card.spanish })}
        @admin_deck
    end

    def find_original
        Deck.find_by_id(self.original_deck)
    end

    def original_creator
        self.find_original.user
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck, optional: true
  validates :english, :spanish, presence: true, :length => {:maximum => 50}
  # validates_uniqueness_of :english, :spanish
end

app/models/deck.rb
class Deck < ApplicationRecord
    belongs_to :user
    has_many :cards, dependent: :destroy
    validates :name, presence: true, :length => {:maximum => 50} 
    validates :cards, :presence => true, :length => {:minimum => 3, :maximum => 50}
    accepts_nested_attributes_for :cards, allow_destroy: true

    def with_cards
        @deck = {
            id: self.id,
            name: self.name,
            level: self.level,
            cards: []
        }
        self.cards.each{ |card| @deck[:cards] << { id: card.id, english: card.english, spanish: card.spanish } }
        @deck
    end

    def admin_cloned?
        AdminDeck.find_by(original_deck: self.id) ? true : false
    end
    
end

app/models/deck_search.rb
class DeckSearch
    attr_accessor :admin_approved, :level, :user_id

    DEFAULT_ATTRS = {
        admin_approved: "",
        level: "", 
        user_id: ""
    }

    def initialize(attributes=DEFAULT_ATTRS)
        attributes.each{ |key, value| self.send("#{key}=", value) }
    end

    def decks 
        Deck.where(self.as_hash)
    end

    def as_hash
        self.as_json.delete_if{|key, value| value == ""}
    end

end

app/models/user.rb
class User < ApplicationRecord
    validates :name, :email, presence: true
    validates :email, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must have @ in between characters" }
    validates_confirmation_of :password 
    has_secure_password
    has_many :decks, dependent: :destroy

end

app/controllers/api_controller.rb
class ApiController < ApplicationController

    def decks
        @decks = API.decks 
        render json: @decks 
    end

end

app/controllers/deck_searches_controller.rb
class DeckSearchesController < ApplicationController
    before_action :validate_admin
    before_action :initialize_search

    def show
    end

    private

    def deck_search_params
        params.permit(:admin_approved, :level, :user_id)
    end

    def search_params?
        deck_search_params != {}
    end

    def initialize_search
        @deck_search = search_params? ? DeckSearch.new(deck_search_params) : DeckSearch.new
    end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
    before_action :deck, only: [:show, :edit, :update, :destroy]
    before_action :validate_user_or_admin, only: [:show, :edit, :update, :destroy]
    
    def index
        @decks = Deck.all
    end

    def new
        @deck = current_user.decks.build
    end

    def create  
        @deck = current_user.decks.build(deck_params)
        if @deck.save
            redirect_to_profile
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @deck.update(deck_params)
            redirect_to_profile
        else
            render :edit
        end
    end

    def destroy
        @deck.destroy
        redirect_to_profile
    end

    private 

    def deck_params
        params.require(:deck).permit(
            :name, :level, :user_id,
            cards_attributes: [ :id, :english, :spanish, :_destroy ]
          )
    end

    def deck
        @deck = Deck.find_by_id(params[:id])
    end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

    def index
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        @user = User.find_by(email: session_params[:email])
        if @user && @user.authenticate(session_params[:password])
            initialize_session
            redirect_to_profile
        else
            # add error to handle this event
            redirect_to '/login'
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    private

    def session_params
        params.require(:user).permit(:email, :password)
    end

    def initialize_session
        session[:user_id] = @user.id
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :current_user, only: [:show, :edit, :update, :destroy]
    before_action :validate_user, only: [:show, :edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save   
            session[:user_id] = @user.id
            redirect_to_profile
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to_profile
        else 
            render :edit
        end
    end

    def destroy
        current_user.destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    private

    def user_params
        params.require(:user).permit(:id, :email, :name, :password, :password_confirmation, :admin, :image)
    end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  
  def index
  end

end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/deck_searches/_deck_table.html.erb
<table>
    <thead>
        <tr>
            <td>Deck Title: </td>
            <td>Approved: </td>
            <td>Level: </td>
            <td>Creator: </td>
            <td>Admin Cloned: </td>
        </tr>
    </thead>

    <tbody>
        <% @deck_search.decks.map do |deck| %>
            <tr>
                <td><%= link_to deck.name, deck_path(deck) %></td>
                <td><%= deck.admin_approved ? "Yes" : "No" %></td>
                <td><%= deck.level %></td>
                <td><%= deck.user.name %></td>
                <td><%= deck.admin_cloned? ? "yes" : "no" %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/deck_searches/_js_search_page.html.erb
<%# YOU ARE HERE - FILL OUT SELECT TAGS AND CREATE JS LOGIC TO FILTER OUT APPROPRIATE DECKS - use element.hidden = true ??? %>

<label>Admin Approved: </label>
<select id="admin-select">
    <option value="All">All</option>
    <option value="Yes">Approved</option>
    <option value="No">Not Approved</option>
</select>
<br>
<label>Level: </label>
<select id="level-select">
    <option value="All">All</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
    <option value="7">7</option>
</select>
<br>
<label>User: </label>
<select id="user-select">
    <option value="All">All</option>
    <% User.all.map do |user| %>
        <option value=<%= user.id %>><%= user.name %></option>
    <% end %>
</select>
<br><br>
<button id="search-button">Submit Search</button>
<br><br><br>
<table>
    <thead>
        <tr>
            <td>Deck Title: </td>
            <td>Approved: </td>
            <td>Level: </td>
            <td>Creator: </td>
        </tr>
    </thead>

    <tbody>
        <% @deck_search.decks.map do |deck| %>
            <tr class="deck-row" id=<%= "deck-#{deck.id}" %>>
                <td class="deck-name"><%= link_to deck.name, deck_path(deck) %></td>
                <td class="deck-admin"><%= deck.admin_approved ? "Yes" : "No" %></td>
                <td class="deck-level"><%= deck.level %></td>
                <td class="deck-user" data-user-id=<%= deck.user.id %>><%= deck.user.name %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/deck_searches/_search_fields.html.erb
<%= form_tag '/deck_search', method: 'get' do %>

    <label>Approved: </label>
    <%= select_tag 'admin_approved', options_for_select([ ["Admin Approved", true], ["Not Admin Approved", false] ], @deck_search.admin_approved), include_blank: "All" %><br>

<%# create Level model, and then use those instances for select_tag %>
    <label>Level: </label>
    <%= select_tag 'level', options_for_select(["1", "2", "3", "4", "5", "6", "7"], @deck_search.level), include_blank: "All" %><br>

    <label>User: </label> 
    <%= select_tag 'user_id', options_for_select(User.all.collect{ |u| [u.name, u.id] }, @deck_search.user_id), include_blank: "All" %><br>
    
    <br>
    
    <%= submit_tag "Search Decks" %>

<% end %>

app/views/deck_searches/show.html.erb
<h1>Search Decks: </h1>

<%= render partial: "search_fields" %>
<%#= render partial: "js_search_page" %>

<br>

COMMENT THIS OUT IF SWITCHING OVER TO JS SEARCH PAGE
<% if @deck_search.decks.length == 0 %>
    <h3>Sorry, no decks match that search.</h3>
<% else %>  
    <%= render partial: "deck_table" %>
<% end %>