config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
 
  resources :users do 
    resources :decks 
  end

  get '/deck_search' => "deck_searches#show"
  get '/admin_resources' => "admin_resources#show"
  resources :admin_decks

  #=> NEED TO ENCORPORATE ADMIN EDITING ABILITIES HERE
  resources :decks #=> should any be excluded? - maybe :new?

  resources :visitors, only: [:index]
  resources :errors, only: [:index]
   
  get '/api/decks' => "api#decks"

end

app/models/user.rb
class User < ApplicationRecord
    validates :name, :email, presence: true
    validates :email, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must have @ in between characters" }
    validates_confirmation_of :password 
    has_secure_password
    has_many :decks, dependent: :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :current_user, only: [:show, :edit, :update, :destroy]
    before_action :validate_user, only: [:show, :edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save   
            session[:user_id] = @user.id
            redirect_to_profile
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to_profile
        else 
            render :edit
        end
    end

    def destroy
        current_user.destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    private

    def user_params
        params.require(:user).permit(:id, :email, :name, :password, :password_confirmation, :admin, :image)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h2>Create your profile! </h2>

<%= form_with model: @user, local: true do |f| %>

    <%= f.label :name, "Name: " %>
    <%= f.text_field :name %><br>

    <%= f.label :email, "Email: " %>
    <%= f.text_field :email %><br>

    <%= f.label :password, "Password: " %>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation, "Confirm Password: " %>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit "Submit Profile!" %>

<% end %>

app/views/users/edit.html.erb
<h2>Edit User Form</h2>

<%= render partial: "form" %>

app/views/users/new.html.erb
<h2>New User Form</h2>

<%= render partial: "form" %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% if @user.admin %>
<h2>(admin)</h2>
<% end %>

<h2>Flash Card Sets:</h2>
<% @user.decks.map do |deck| %>
    <li>
        <%= link_to deck.name, user_deck_path(@user, deck) %>
    </li>
<% end %>


<br><br>
<button><%= link_to "Create Set", new_user_deck_path(@user) %></button>