config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
 
  resources :users do 
    resources :decks 
  end

  get '/deck_search' => "deck_searches#show"
  get '/admin_resources' => "admin_resources#show"
  resources :admin_decks

  #=> NEED TO ENCORPORATE ADMIN EDITING ABILITIES HERE
  resources :decks #=> should any be excluded? - maybe :new?

  resources :visitors, only: [:index]
  resources :errors, only: [:index]
   
  get '/api/decks' => "api#decks"

end

app/models/API.rb
class API 

    def self.decks
        @decks = Deck.all.where("level > 0").map{ |deck| deck.with_cards }
    end

end

app/models/admin_deck.rb
class AdminDeck < Deck
    validates :original_deck, uniqueness: true

    def self.new_from_existing(deck_object, admin_id)
        deck_hash = {
            name: deck_object.name,
            level: deck_object.level,
            user_id: admin_id,
            original_deck: deck_object.id
        }
        @admin_deck = self.new(deck_hash)
        deck_object.cards.each{|card| @admin_deck.cards.build({ english: card.english, spanish: card.spanish })}
        @admin_deck
    end

    def find_original
        Deck.find_by_id(self.original_deck)
    end

    def original_creator
        self.find_original.user
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck, optional: true
  validates :english, :spanish, presence: true, :length => {:maximum => 50}
  # validates_uniqueness_of :english, :spanish
end

app/models/deck.rb
class Deck < ApplicationRecord
    belongs_to :user
    has_many :cards, dependent: :destroy
    validates :name, presence: true, :length => {:maximum => 50} 
    validates :cards, :presence => true, :length => {:minimum => 3, :maximum => 50}
    accepts_nested_attributes_for :cards, allow_destroy: true

    def with_cards
        @deck = {
            id: self.id,
            name: self.name,
            level: self.level,
            cards: []
        }
        self.cards.each{ |card| @deck[:cards] << { id: card.id, english: card.english, spanish: card.spanish } }
        @deck
    end

    def admin_cloned?
        AdminDeck.find_by(original_deck: self.id) ? true : false
    end
    
end

app/models/deck_search.rb
class DeckSearch
    attr_accessor :admin_approved, :level, :user_id

    DEFAULT_ATTRS = {
        admin_approved: "",
        level: "", 
        user_id: ""
    }

    def initialize(attributes=DEFAULT_ATTRS)
        attributes.each{ |key, value| self.send("#{key}=", value) }
    end

    def decks 
        Deck.where(self.as_hash)
    end

    def as_hash
        self.as_json.delete_if{|key, value| value == ""}
    end

end

app/models/user.rb
class User < ApplicationRecord
    validates :name, :email, presence: true
    validates :email, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must have @ in between characters" }
    validates_confirmation_of :password 
    has_secure_password
    has_many :decks, dependent: :destroy

end

app/controllers/admin_decks_controller.rb
class AdminDecksController < ApplicationController
    before_action :admin_deck, only: [:show, :edit, :update, :destroy]

    def index
        @admin_decks = AdminDeck.all
    end

    def new
        @admin_deck = new_admin_deck
        if @admin_deck.save
            redirect_to admin_deck_path(@admin_deck)
        else
            # error
            binding.pry
        end
    end

    def show
    end

    def edit
    end

    def update
        if @admin_deck.update(admin_deck_params)
            redirect_to admin_decks_path
        else
            render :edit
        end
    end

    def destroy
        @admin_deck.destroy
        redirect_to admin_decks_path
    end

    private

    def admin_deck_params
        params.require(:admin_deck).permit(
            :name, :level,
            cards_attributes: [ :id, :english, :spanish, :_destroy ]
          )
    end

    def new_admin_deck
        original_deck = Deck.find_by_id(params[:format])
        admin_deck = AdminDeck.new_from_existing(original_deck, current_user.id)
    end

    def admin_deck
        @admin_deck = AdminDeck.find_by_id(params[:id])
    end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController

    def decks
        @decks = API.decks 
        render json: @decks 
    end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
    before_action :deck, only: [:show, :edit, :update, :destroy]
    before_action :validate_user_or_admin, only: [:show, :edit, :update, :destroy]
    
    def index
        @decks = Deck.all
    end

    def new
        @deck = current_user.decks.build
    end

    def create  
        @deck = current_user.decks.build(deck_params)
        if @deck.save
            redirect_to_profile
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @deck.update(deck_params)
            redirect_to_profile
        else
            render :edit
        end
    end

    def destroy
        @deck.destroy
        redirect_to_profile
    end

    private 

    def deck_params
        params.require(:deck).permit(
            :name, :level, :user_id,
            cards_attributes: [ :id, :english, :spanish, :_destroy ]
          )
    end

    def deck
        @deck = Deck.find_by_id(params[:id])
    end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

    def index
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        @user = User.find_by(email: session_params[:email])
        if @user && @user.authenticate(session_params[:password])
            initialize_session
            redirect_to_profile
        else
            # add error to handle this event
            redirect_to '/login'
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    private

    def session_params
        params.require(:user).permit(:email, :password)
    end

    def initialize_session
        session[:user_id] = @user.id
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :current_user, only: [:show, :edit, :update, :destroy]
    before_action :validate_user, only: [:show, :edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save   
            session[:user_id] = @user.id
            redirect_to_profile
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to_profile
        else 
            render :edit
        end
    end

    def destroy
        current_user.destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    private

    def user_params
        params.require(:user).permit(:id, :email, :name, :password, :password_confirmation, :admin, :image)
    end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  
  def index
  end

end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin_decks/_card_fields.html.erb
<tr class="card-row">
    <td>
        <%= ff.text_field :english %>
    </td>
    <td>
        <%= ff.text_field :spanish %>
    </td>
    <td>
        <button>
            <%= link_to_remove_nested(ff, fields_wrapper_selector: 'card-row', link_text: "remove") %>
        </button>
    </td>
</tr>

app/views/admin_decks/_form.html.erb
<%= form_with model: @admin_deck, local: true do |f| %>
    <%= f.label :name, "Name: " %>
    <%= f.text_field :name %>

    <%= f.label :level, "Level: " %>
    <%= f.number_field :level, in: 1..8, step: 1 %>

    <br><br>

    <h3><strong>CARDS:</strong></h3>
    <table>
        <thead>
            <tr>
                <td>English:</td>
                <td>Spanish:</td>
            </tr>
        </thead>

        <tbody id="nested-cards-table" class="fields">
            <%= f.fields_for :cards do |ff| %>
                <%= render 'card_fields', ff: ff %>
            <% end %>
        </tbody>
    </table>
    
    <br>

    <button>
        <%= link_to_add_nested(f, :cards, '#nested-cards-table', partial_form_variable: :ff) %>
    </button>

    <br><br>
    
    <%= f.submit "Submit Deck as Admin Approved" %>
    
<% end %>

app/views/admin_decks/edit.html.erb
<h2>Edit: <%= @admin_deck.name %></h2>

<%= form_with model: @admin_deck, local: true do |f| %>
    <%= f.label :name, "Name: " %>
    <%= f.text_field :name %>

    <%= f.label :level, "Level: " %>
    <%= f.number_field :level, in: 1..8, step: 1 %>

    <br><br>

    <h3><strong>CARDS:</strong></h3>
    <table>
        <thead>
            <tr>
                <td>English:</td>
                <td>Spanish:</td>
            </tr>
        </thead>

        <tbody id="nested-cards-table" class="fields">
            <%= f.fields_for :cards do |ff| %>
                <%= render 'card_fields', ff: ff %>
            <% end %>
        </tbody>
    </table>
    
    <br>

    <button>
        <%= link_to_add_nested(f, :cards, '#nested-cards-table', partial_form_variable: :ff) %>
    </button>

    <br><br>
    
    <%= f.submit "Submit Flash Cards" %>
    
<% end %>

app/views/admin_decks/index.html.erb
<h1>Admin Approved Decks:</h1>

<ul>
<% @admin_decks.map do |deck| %>
    <li>
        <%= link_to deck.name, admin_deck_path(deck) %>
    </li>
<% end %>
</ul>

app/views/admin_decks/show.html.erb
<h1>Admin Deck</h1>

<h2><%= @admin_deck.name %></h2>
<h4>Level: <%= @admin_deck.level %></h4>

<table>
    <tbody>
        <tr>
            <td>ENGLISH:</td>
            <td>SPANISH:</td>
        </tr>

        <% @admin_deck.cards.map do |card| %>
            <tr>
                <td><%= card.english %></td>
                <td><%= card.spanish %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br><br>

<button><%= link_to "Edit Set", edit_admin_deck_path(@admin_deck) %></button>

<br><br>
    
<button>
    <%= link_to "Delete Set", @admin_deck, method: 'delete', data: { confirm: "Are you sure?" } %>
</button>

<br><br>
  

app/views/visitors/index.html.erb
<h1>Visitors Page</h1>

<h3> Content to add: </h3>

<ul>
    <li>Brief description of what the app does</li>
    <li>Demo video</li>
    <li>Make a deck (but don't save)</li>
    <li>Demo video for frontend app</li>
</ul>