config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
 
  resources :users do 
    resources :decks 
  end

  get '/deck_search' => "deck_searches#show"
  get '/admin_resources' => "admin_resources#show"
  resources :admin_decks

  #=> NEED TO ENCORPORATE ADMIN EDITING ABILITIES HERE
  resources :decks #=> should any be excluded? - maybe :new?

  resources :visitors, only: [:index]
  resources :errors, only: [:index]
   
  get '/api/decks' => "api#decks"

end

app/models/deck.rb
class Deck < ApplicationRecord
    belongs_to :user
    has_many :cards, dependent: :destroy
    validates :name, presence: true, :length => {:maximum => 50} 
    validates :cards, :presence => true, :length => {:minimum => 3, :maximum => 50}
    accepts_nested_attributes_for :cards, allow_destroy: true

    def with_cards
        @deck = {
            id: self.id,
            name: self.name,
            level: self.level,
            cards: []
        }
        self.cards.each{ |card| @deck[:cards] << { id: card.id, english: card.english, spanish: card.spanish } }
        @deck
    end

    def admin_cloned?
        AdminDeck.find_by(original_deck: self.id) ? true : false
    end
    
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
    before_action :deck, only: [:show, :edit, :update, :destroy]
    before_action :validate_user_or_admin, only: [:show, :edit, :update, :destroy]
    
    def index
        @decks = Deck.all
    end

    def new
        @deck = current_user.decks.build
    end

    def create  
        @deck = current_user.decks.build(deck_params)
        if @deck.save
            redirect_to_profile
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @deck.update(deck_params)
            redirect_to_profile
        else
            render :edit
        end
    end

    def destroy
        @deck.destroy
        redirect_to_profile
    end

    private 

    def deck_params
        params.require(:deck).permit(
            :name, :level, :user_id,
            cards_attributes: [ :id, :english, :spanish, :_destroy ]
          )
    end

    def deck
        @deck = Deck.find_by_id(params[:id])
    end

end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_clone_button.html.erb
<button>
    <%= link_to "Clone Set", new_admin_deck_path(@deck) %>
</button>

<br><br>
 
 

app/views/decks/_deck_form.html.erb
<%= form_with model: [current_user, @deck], local: true do |f| %>
    <%= f.label :name, "Name: " %>
    <%= f.text_field :name %>

    <%= f.label :level, "Level: " %>
    <%= f.number_field :level, in: 1..8, step: 1 %>

    <br><br>

    <h3><strong>CARDS:</strong></h3>
    <table>
        <thead>
            <tr>
                <td>English:</td>
                <td>Spanish:</td>
            </tr>
        </thead>

        <tbody id="nested-cards-table" class="fields">
            <%= f.fields_for :cards do |ff| %>
                <%= render 'card_fields', ff: ff %>
            <% end %>
        </tbody>
    </table>
    
    <br>

    <button>
        <%= link_to_add_nested(f, :cards, '#nested-cards-table', partial_form_variable: :ff) %>
    </button>

    <br><br>
    
    <%= f.submit "Submit Flash Cards" %>
    
<% end %>

app/views/decks/_edit_button.html.erb
<button><%= link_to "Edit Set", edit_user_deck_path(@deck.user, @deck) %></button>

<br><br>
    
<button>
    <%= link_to "Delete Set", [current_user, @deck], method: 'delete', data: { confirm: "Are you sure?" } %>
</button>

<br><br>
  

app/views/decks/_search_fields.html.erb
<%# binding.pry %>
<%= form_tag '/decks/scoped', method: 'post' do %>
  
    <label>Approved: </label>
    <%= select_tag 'admin_approved', options_for_select(["Admin Approved", "Not Admin Approved" ]), include_blank: "All" %><br>

<%# create Level model, and then use those instances for select_tag %>
    <label>Level: </label>
    <%= select_tag 'level', options_for_select(["1", "2", "3", "4", "5", "6", "7"]), include_blank: "All" %><br>

    <label>User: </label> 
    <%= select_tag 'user_id', options_for_select(@users.collect{ |u| [u.name, u.id] }), include_blank: "All" %><br>
    
    <br>
    
    <%= submit_tag "Search Decks" %>

<% end %>

app/views/decks/edit.html.erb
<h1>Edit Flash Card Set</h1>

<%= render partial: "deck_form" %>

<br><br>

<button><%= link_to "Back to Deck", user_deck_path(current_user, @deck) %></button>

app/views/decks/index.html.erb
<h1>Decks Index</h1>

<ul>

    <% @decks.map do |deck| %>
        <li>
            <%= deck.name %>  
        </li>
    <% end %>

</ul>

app/views/decks/new.html.erb
<h1>New Flash Card Set</h1>

<%= render partial: "deck_form" %>

app/views/decks/show.html.erb
<h2><%= @deck.name %></h2>
<h4>Level: <%= @deck.level %></h4>
<h4>Admin Approved: <%= @deck.admin_cloned? ? "TRUE" : "FALSE" %></h4>

<table>
    <tbody>
        <tr>
            <td>ENGLISH:</td>
            <td>SPANISH:</td>
        </tr>

        <% @deck.cards.map do |card| %>
            <tr>
                <td><%= card.english %></td>
                <td><%= card.spanish %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br><br>

<% if @deck.user == @user %>
    <%= render partial: "edit_button" %>
<% end %>

<% if @user.admin %>
    <%= if @deck.admin_cloned? %>
        <h3>- Already Cloned -</h3>
    <% else %>
        <%= render partial: "clone_button" %>
    <% end %>
<% end %>